name: Release

on:
  push:
    branches: [ main, tools ]

jobs:
  windows:
    strategy:
      matrix:
        arch: ["x86-64-vnni512", "x86-64-avx512", "x86-64-bmi2", "x86-64-modern", "x86-64"]
    runs-on: windows-latest

    steps:
      - uses: al-cheb/configure-pagefile-action@v1.2
        with:
            minimum-size: 16GB
            maximum-size: 16GB
            disk-root: "C:"

      - uses: actions/checkout@v3

      - name: make
        run: cd src && make clean && make -j build COMP=mingw ARCH=${{ matrix.arch }} EXE=${{ matrix.arch }}.exe largeboards=yes && strip ${{ matrix.arch }}.exe

      - uses: actions/upload-artifact@v3
        with:
          name: fairy-stockfish
          path: src/x86-64*.exe
  linux:
    strategy:
      matrix:
        arch: ["x86-64-bmi2"]
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3

      - name: make
        run: cd src && make clean && make -j build COMP=gcc ARCH=${{ matrix.arch }} EXE=${{ matrix.arch }} largeboards=yes && strip fairy-stockfish-largeboards_${{ matrix.arch }}

      - uses: actions/upload-artifact@v3
        with:
          name: fairy-stockfish-linux
          path: src/x86-64*
